### ISSUE TITLE
MetadataReferenceFeature is obsolete: (https://aka.ms/AA1x4gg)

### ISSUE THREAD

**Issue by cyberh0me** [aspnet/AspNetCore.Docs.de-de#38]
please could you update the FeaturesController sample accordingly

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 2784a724-e940-4c14-3b50-b063f78c2ee5
* Version Independent ID: 41175c3a-8cb5-856b-a7e0-931edb6394db
* Content: [Anwendungsparts in ASP.NET Core](https://docs.microsoft.com/de-de/aspnet/core/mvc/advanced/app-parts?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/mvc/advanced/app-parts.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/mvc/advanced/app-parts.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-mvc**
* GitHub Login: @ardalis
* Microsoft Alias: **riande**

**Comment by CeciAc** [comment]
Hello, @cyberh0me

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/12316

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
