### ISSUE TITLE
A @using statement is needed to use TodoItem.cs in this component.

### ISSUE THREAD

**Issue by Saik19922** [aspnet/AspNetCore.Docs.de-de#39]
At step 5 where TodoItem.cs is created and the TodoItem class is declared, todo.razor will also need a @using &lt;Name of your App&gt; directive to make the TodoItem class available.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 36e7dc3c-54c4-35de-203e-d230869e8417
* Version Independent ID: dc5b52d5-c8c6-1440-6b3a-fda898167d0c
* Content: [Erstellen Ihrer ersten Blazor-App](https://docs.microsoft.com/de-de/aspnet/core/tutorials/build-your-first-blazor-app?view=aspnetcore-3.0#feedback)
* Content Source: [aspnetcore/tutorials/build-your-first-blazor-app.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/tutorials/build-your-first-blazor-app.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
@CeciAc I moved the issue over to our repo for work :point_right: https://github.com/aspnet/AspNetCore.Docs/issues/12404. I'll get it done today.

**Comment by CeciAc** [comment]
Hello, @Saik19922

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/12404

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
