### ISSUE TITLE
Example Code is distorted

### ISSUE THREAD

**Issue by MacOkieh** [aspnet/AspNetCore.Docs.de-de#44]
Every line of code examples that is marked yellow is empty or distorted and missing important information (var...new, var...await)

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 28ae5984-32b1-13b6-7430-6a28460b42ce
* Version Independent ID: 20dc0e1d-d582-c091-8243-cefbb1825397
* Content: [Razor-Seiten-Komponententests in ASP.NET Core](https://docs.microsoft.com/de-de/aspnet/core/test/razor-pages-tests?view=aspnetcore-2.2#feedback)
* Content Source: [aspnetcore/test/razor-pages-tests.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/test/razor-pages-tests.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-test**
* GitHub Login: @guardrex
* Microsoft Alias: **riande**

**Comment by guardrex** [comment]
Hello @MacOkieh ... We have an internal issue open with docs engineering to address it. https://github.com/aspnet/AspNetCore.Docs/issues/13143

**Comment by CeciAc** [comment]
Hello, @

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/aspnet/AspNetCore.Docs/issues/13143 
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
