### ISSUE TITLE
OpenInfo is Info now

### ISSUE THREAD

**Issue by sk2andy** [aspnet/AspNetCore.Docs.de-de#47]
Swashbuckle changed the name of the class OpenInfo to Info

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: f34eea37-51a4-6227-f5ed-6501624ad045
* Version Independent ID: 2994cf60-0cb7-afa2-20b8-7e2b1117f964
* Content: [ASP.NET Core-Web-API-Hilfeseiten mit Swagger/OpenAPI](https://docs.microsoft.com/de-de/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-2.2)
* Content Source: [aspnetcore/tutorials/web-api-help-pages-using-swagger.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/tutorials/web-api-help-pages-using-swagger.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @RSuter
* Microsoft Alias: **scaddie**

**Comment by srvbpigh** [comment]
Hello, @sk2andy
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @sk2andy

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/13440

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
