### ISSUE TITLE
Dialog does not show in Visual Studio

### ISSUE THREAD

**Issue by atomroflman** [aspnet/AspNetCore.Docs.de-de#60]
In the section: Add the SignalR client library
You say: "In Solution Explorer, right-click the project, and select Add > Client-Side Library" wich brings me to the libman.json instead of the shown dialog.

Betriebsystemname	Microsoft Windows 10 Pro
Version	10.0.18362 Build 18362

[Hier Feedback eingeben]
---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0dd2991d-c22d-ad0f-80b6-bd1b503db8f3
* Version Independent ID: 5e3fbe1d-c97f-9940-4f0c-067d4b2112b1
* Content: [Erste Schritte mit ASP.NET Core SignalR](https://docs.microsoft.com/de-de/aspnet/core/tutorials/signalr?view=aspnetcore-3.0&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/signalr.md](https://github.com/aspnet/AspNetCore.Docs.de-de/blob/live/aspnetcore/tutorials/signalr.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @bradygaster
* Microsoft Alias: **bradyg**

**Comment by srvbpigh** [comment]
Hello, @atomroflman
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @atomroflman

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/aspnet/AspNetCore.Docs/issues/15707

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
